# Generated by Django 2.2.6 on 2019-10-17 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicadmin_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_bundle_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('test_charfield', models.CharField(blank=True, default='', max_length=255, verbose_name='')),
                ('bundle', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dynamicadmin_tests.TestBundle')),
            ],
            options={
                'verbose_name': 'test bundle 1',
                'verbose_name_plural': 'test bundle 1',
            },
        ),
    ]
