# Generated by Django 2.2.6 on 2019-10-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamicadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBundle',
            fields=[
                ('bundle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamicadmin.Bundle')),
            ],
            bases=('dynamicadmin.bundle',),
        ),
    ]
