# Generated by Django 2.2.6 on 2019-10-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_bundle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_options', models.CharField(blank=True, default='default value', max_length=255, verbose_name='')),
                ('test_charfield', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('bundle', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tests_bundle_app.TestBundle')),
            ],
            options={
                'verbose_name': 'test bundle',
            },
        ),
    ]
