# Generated by Django 2.2.6 on 2019-10-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_dynamic_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_bundle',
        ),
    ]
